### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by masmc05** [ArcAios26/supersaturation#1]
1. when the mod will officialy release on 1.16.5? it works but on search for mods in launchers it doesn't appear 
2. Information about oversaturation in F3 information
3. An overlay in game to see how much saturation we have (like in appleskin, but in multiple layers)

**Comment by ArcAios26** [comment]
I am closing this with the update officially bringing it to 1.16.5 as well as updating the build against 1.16.5 and newest forge for that version. I am going to open separate issues for number 2 and 3 for tracking purposes as each will be worked on individually.
